[package]
name = "rustnodes"
version = "0.1.0"
authors = ["Ido David <kaki>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httparse="1.5.1"
json="0.12.4"